### ISSUE TITLE
Schedule pool change

### ISSUE THREAD

**Issue by ghost** [getminera/minera#131]
It would be neat if you can program minera to switch to pool x or pools x based on a certain time of the day or date

So it would allow me to schedule multi pool at 8:00am est on Monday and multitash at 8 on Tuesday or what have you

**Comment by msaleh3000** [comment]
It would even be great to be able to schedule pool change exactly like the donation pool by mining a specific pool from a set time and after that return to the original pool unless there are other pools scheduled. 
Thank you for the great work.

**Comment by michelem09** [comment]
Guys please give a try to the new Minera (beta) https://app.getminera.com
