### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by ghost** [getminera/minera#132]
allow the ability to grant users access to sections and read/write access to various sections

**Comment by michelem09** [comment]
Are you talking about some kind of users and permissions management?

**Comment by computeronix** [comment]
Correct

Sent from my iPhone

On Apr 2, 2015, at 3:21 AM, Michele Marcucci <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you talking about some kind of users and permissions management?

-
