### ISSUE TITLE
Add an automatic pool switcher 

### ISSUE THREAD

**Issue by michelem09** [getminera/minera#146]
As requested here: https://bitcointalk.org/index.php?topic=596620.msg12236912#msg12236912 I could add an automatic pool switcher based on various thing.

Probably the simplest one could be an automatic rotation based on time, then I could think about a more complex scheduler and even to a switcher based on profitability.

I need to add also a "coin" data (what coin are you mining with this pool?) for each pool inserted.

**Comment by 0xicl33n** [comment]
cant you just add --rotate 60 (minuters)

in the manual options?  thats how i used to run it before i got minera.

**Comment by michelem09** [comment]
Yes that could be a starting point but I was thinking about something more complex done by Minera itself and not by the miner software, also because the `--rotate` option is not a standard option every miners have.

**Comment by rickardostupart** [comment]
I am unable to add a pool. It only shows donation pool.

**Comment by tekcomm** [comment]
I am looking into adding coinwarz.com api to check the most profitable mining. Ill post a update this week.

**Comment by tekcomm** [comment]
Im looking at hacking in support for it by add https://github.com/Stratehm/stratum-proxy and then using the api to enable/disable pools. Based on the coinwarz api.
