### ISSUE TITLE
Algorithm switching

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [getminera/minera#156]
As with pool switching, ability to switch algorithm is desirable.

**Comment by michelem09** [comment]
Why should you have to switch algo?

**Comment by ParaplegicRacehorse** [comment]
It's not an option of ASIC miners. But CPU and GPU miners have the option to switch algos to whatever is most profitable to mine. Or because we want to support one coin over another. Or just for an excuse to fiddle with the software.

**Comment by michelem09** [comment]
Mmm ok and could you use cpuminer-multi without problems in MInera? Is it a cgminer fork with same API? Because otherwise this doesn't make much sense

**Comment by ParaplegicRacehorse** [comment]
What works with tpruvot's cpuminer-multi 1.3.1 (as of 2017-02-04@22:30GMT-9)
* Minera will start it and it will run.

What does not work:
* Minera cannot stop it. Needed to `SIGKILL` cpuminer from a shell when I wanted to stop.
* Minera incorrectly displays cpuminer as a non-running miner in the interface.
* ALL config options need to go into the "additional" options box. cpuminer* lacks an API so can't use those misfeatures.

That said, with the right shell scripts, it would support algorithm or pool changes every bit as well as cgminer or ccminer. The scripts, themselves, could be [relatively] simple. (Stop miner. Restart with new options or config file). Slightly more complicated would be a script to read the config from a CSV file and pass those parameters to the commandline.

**Comment by michelem09** [comment]
So, sorry for the late, is it showing the stats too?
Can you point me to the Github repo you used for cpuminer-multi?
Thanks
