### ISSUE TITLE
System Temp for the dashboard from lmsensors in one line straight into redis

### ISSUE THREAD

**Issue by ghost** [getminera/minera#167]
Here's what I am using for the system temp it pulls it in one line from the lm-sensors and stores it directly in the redis. I just use a cron for it.
<pre>
echo  $(sensors -f   | grep "temp1" | grep therm | awk '{print $2}') | xargs -I {}
 redis-cli -p 6379 set dashboard_temp "{}" </pre>

**Comment by michelem09** [comment]
Are you talking about Minera installed on a non-raspberry system?

**Comment by tekcomm** [comment]
Yes, but you you wanted it to work all all systems you could do this.
<pre>
 find /sys/devices/platform/ | grep hwmon/hwmon0/temp1_input | xargs cat | rev | sed 's/.\{2\}\([1-9]\)/.\1/' | rev | xargs -I {} redis-cli -p 6379 set dashboard_temp "{}" </pre> that will work on any system

**Comment by michelem09** [comment]
Thanks I will review it soon.

**Comment by tekcomm** [comment]
It takes the temp from the first hwmon lmsensors which is allways the cpu. The rest is wierd shit I like to do with sed.
47000 is 47.0 C
so I reverse it because the temp can go over 3 digits
00074 cut the last two numbers since  are allways 0
074 then sed out the first number and add a period
0.74 then reverse it and it keeps any bugs out.
47.0C :)

**Comment by tekcomm** [comment]
No hit me on skype at jsktek
for the rasberry
/sys/class/hwmon/hwmon*/temp1_*

**Comment by tekcomm** [comment]
Hit me on skype at jskte

**Comment by michelem09** [comment]
Sorry I'm busy now

**Comment by tekcomm** [comment]
No prob just add me when your not busy, I hacked a certain companies
website and called them up about it and I get phone call whenever there
miners are going on sale and two weeks advanced notice :)

**Comment by tekcomm** [comment]
I am waiting on about dozen asic machines and want to fix the bugs so if
you have some wierd ones let me know.

**Comment by tekcomm** [comment]
Here is the final version of the temp fix for you to use
This goes in the installer bash script.
<pre>
find /sys/devices/platform/ | grep hwmon/hwmon0/temp1_input | xargs -I {} ln -s "{}" /var/www/input_temp1
</pre>
It creates a link to the hardware temp to /var/www/temp1_input
This is added to the top of top application/controller/unit.php and passes the temp from php to javascript.

<pre>
<script type="text/javascript">
var data="1";
data.temp.value=<?php filename = '/var/www/input1_temp';
$data = file($filename);
foreach ($data as $line_num=>$line)
{
echo $line;
}
?>
</script>
</pre>

**Comment by michelem09** [comment]
It's not so standard my RPI3 cannot get anything neither a couple of Ubuntu cloud server.
I should work on this.

**Comment by tekcomm** [comment]
Try
apt-get install lm-sensors fan control
Its standardized.

**Comment by tekcomm** [comment]
<pre>
#!/bin/bash
cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp)
cpuTemp1=$(($cpuTemp0/1000))
cpuTemp2=$(($cpuTemp0/100))
cpuTempM=$(($cpuTemp2 % $cpuTemp1))

gpuTemp0=$(/opt/vc/bin/vcgencmd measure_temp)
gpuTemp0=${gpuTemp0//\'/º}
gpuTemp0=${gpuTemp0//temp=/}

echo CPU Temp: $cpuTemp1"."$cpuTempM"ºC"</pre>
That will give you cpu and cpu temp on the rp3

**Comment by tekcomm** [comment]
You can read it directly through php into a javascript var as in the previous example.

**Comment by tekcomm** [comment]
The senors wiki is the best for the info
https://wiki.archlinux.org/index.php/lm_sensors

**Comment by tekcomm** [comment]
My RP3 unfortunately met a untimely death due to coffee, My new one is coming this week.

**Comment by tekcomm** [comment]
The clouds will not work because they are using Virtio I/O virtualization.
