### ISSUE TITLE
#Feature Im adding Nvidia cuda 9 ccminer tvprout support.

### ISSUE THREAD

**Issue by ghost** [getminera/minera#168]
Im adding nvidia cuda 9 support with ccminer https://github.com/tpruvot/ccminer
There is a repository setup for the cuda 9 devel driver and it performs at almost 200% faster.

**Comment by michelem09** [comment]
Has Ccminer the same API of Cgminer?

**Comment by tekcomm** [comment]
ccMiner 1.5 Fork by tpruvot With Websocket API Example Available
<http://cryptomining-blog.com/3987-new-ccminer-1-5-fork-by-tpruvot-with-websocket-api-example-available/>

since 1.5

**Comment by tekcomm** [comment]
I got it working it. Please add it along with a tesla k80 and p100 ;)
It requires the Aug 2017 release of ccminer. 
https://github.com/tpruvot/ccminer/archive/cuda-9.zip

Nvidia July beta linux driver. "NVIDIA-Linux-x86_64-384.59.run "
http://www.nvidia.com/Download/driverResults.aspx/120917/en-us

Nvidia Cuda 9 Deveoper Driver
https://developer.nvidia.com/cuda-release-candidate-download

And a Tesla P100 in a pear tree :)

<pre>
ccminer  -a scrypt -o stratum+tcp://us.coin-miners.info:6432 -u user -p password  -b --api-remote --api-bind=4028 --api-allow=127.0.0.1,192.168.1.9
</pre>

**Comment by tekcomm** [comment]
The api  which needs some things added to minera is here 
https://github.com/tpruvot/ccminer/blob/cuda-9/api/local-sample.php
https://github.com/tpruvot/ccminer/blob/cuda-9/api/index.php
https://github.com/tpruvot/ccminer/tree/cuda-9

**Comment by michelem09** [comment]
Is the stats working on Minera with ccMiner?

**Comment by tekcomm** [comment]
I will look into the stats issue this week, I was busy building a emulator
the the minera latest.img under ubuntu using qemu

**Comment by Raginglikeaboss** [comment]
@tekcomm

Fantastic work @tekcomm!  Glad to see you working to help @michelem09 improve miners which is already the gold standard for Raspberry Pi mining.

Really excited to see this added support.

**Comment by anorganix** [comment]
@tekcomm 

Thanks for your contibution. Is there any update on ccminer integration?
Thanks!

**Comment by tekcomm** [comment]
Unfortunately, I am waiting on a 1070 to test with. I have been busy
working on arm7hf hard floats powering asic's.

**Comment by tekcomm** [comment]
Back from winter break :) This is on the todo list still along with a back-ordered 1070
