### ISSUE TITLE
rc.local not running due to issue.

### ISSUE THREAD

**Issue by tekcomm** [getminera/minera#170]
rc.local is failing to start because
#!/bin/sh
needs to be changed to 
#!/bin/bash

**Comment by tekcomm** [comment]
fyi, Im running the latest image in qemu-system-arm. Then installing https://github.com/michelem09/minera/archive/developing.zip

Im using  to remove php5
<pre> 
sudo apt-get -y purge `dpkg -l | grep php| awk '{print $2}' |tr "\n" " "`
rm -rf /etc/php5
</pre>

Then to install php7
<pre>
sudo su
apt-get update --fix-missing
apt-get -y install apt-transport-https lsb-release ca-certificates
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
apt-get update
</pre>

I also had to change minera_install.sh
libssl1.0-dev to libssl-dev 
and the install worked fine.

**Comment by michelem09** [comment]
Thanks I will fix that. For PHP7.0 Minera 0.8.0 has it by default (I should release it in few days)
