### ISSUE TITLE
Gridseed Black not connecting to certain pools using Bfgminer.

### ISSUE THREAD

**Issue by Tmerlo** [getminera/minera#172]
When I use bfgminer I can connect to litecoinpool but no other pools that I tried such as hash-to-coins or Aikapool. They are reported as dead.

When I use Cgminer it can connect to the reported dead pools fine but blades in the asic miner start going red and shutting down after awhile. But it does work for awhile so the pool infor, username and password are correct.

log:
 [2017-08-31 18:49:26] Pool: 0  URL: stratum+tcp://stratum.aikapool.com:7938  User: ********  Password: x
 [2017-08-31 18:49:26] Press any key to exit, or BFGMiner will try again in 15s.
 [2017-08-31 18:49:41] Testing pool stratum+tcp://stratum.aikapool.com:7938
 [2017-08-31 18:49:42] Closing socket for stratum pool 0
 [2017-08-31 18:49:43] Closing socket for stratum pool 0
 [2017-08-31 18:49:43] Closing socket for stratum pool 0
 [2017-08-31 18:49:43] No servers were found that could be used to get work from.
 [2017-08-31 18:49:43] Please check the details from the list below of the servers you have input
 [2017-08-31 18:49:43] Most likely you have input the wrong URL, forgotten to add a port, or have not set up workers
 [2017-08-31 18:49:43] Pool: 0  URL: stratum+tcp://stratum.aikapool.com:7938  User: ********  Password: x
 [2017-08-31 18:49:43] Press any key to exit, or BFGMiner will try again in 15s.

Settings:
/usr/bin/screen -dmS bfgminer /var/www/minera/minera-bin/bfgminer --scrypt -S gsd:all --set gsd:clock=800 -c /var/www/minera/conf/miner_conf.json

{
    "api-listen": true,
    "api-allow": "W:127.0.0.1",
    "log-file": "\/var\/log\/minera\/bfgminer.log",
    "pools": [
        {
            "url": "stratum+tcp:\/\/stratum.aikapool.com:7938",
            "user": "********",
            "pass": "x"
        }
    ]
}

**Comment by Tmerlo** [comment]
Update:

I changed my config to : 
--scrypt -S gsd:all --set gsd:clock=800 --scrypt -o stratum+tcp://stratum.aikapool.com:7938 -u ******** -p x

forcing the pool info into the command line and bfgminer works but minera still says it's active but dead. everything else sees to be happily hashing away fine and the pool is reporting work being done.

Could something be wrong with the way the json config is being generated?

**Comment by michelem09** [comment]
It's not a Minera issue, you should check it with Bfgminer authors. And are you sure is it working? I don't think your changes do much, you simply moved the config from a file to the command line, nothing to do with your problem.

**Comment by Tmerlo** [comment]
You are correct. That's exactly what I did. I moved the pool config from the config file that is generated by minera to the command line and it's mining now. 

If I don't do that minera says the pool is dead and doesn't mine at all.

If I do that minera still says the pool is dead but it mines. 

![image](https://user-images.githubusercontent.com/8467068/29973684-659ae5bc-8efe-11e7-9483-7bc9b0f07d5b.png)

**Comment by michelem09** [comment]
Are you using `stratum+tcp://` in the pool config?

**Comment by Tmerlo** [comment]
Yes,

![image](https://user-images.githubusercontent.com/8467068/29974844-3cea4366-8f02-11e7-88f7-35b032bee744.png)

**Comment by michelem09** [comment]
That's weird, can you check the config file from the system? It's in /var/www/minera/conf/miner_conf.json
Just do a `cat /var/www/minera/conf/miner_conf.json`

**Comment by Tmerlo** [comment]
That's odd. What's with th "\/"? is it supposed to be like that?

![image](https://user-images.githubusercontent.com/8467068/29975169-6fbe1d8e-8f03-11e7-8c4e-24dcfc96b1cf.png)

**Comment by michelem09** [comment]
It must be a problem with Bfgminer, I have it too. I switched to Cgminer DmaxL and it works very well.

**Comment by Tmerlo** [comment]
I tried DmaxL as well. It works fine for about 10 minutes then my blades in my gridseed start going grey on Minera and not submitting shares.

**Comment by Tmerlo** [comment]
I guess I can just schedule to restart the miner every hour or so.

**Comment by michelem09** [comment]
What about Cpuminer? It should be the best one for Gridseed.

**Comment by Tmerlo** [comment]
Didn't think to try that. I'll give it a shot.

**Comment by Tmerlo** [comment]
It seems to be working. I'll let it run for awhile and see how it goes. Thanks.

**Comment by Raginglikeaboss** [comment]
Just as @michelem09 said, CPUMiner in my experience, I've owned more than 30+ of these G-Blade Towers and 80+ of the smaller G-Blade's, and I've found without a doubt CPUMiner to be the best option for them.

Typically running them at a frequency of 800-825 works best.  The good units can hit 837.5, but I found 812.5 to be the most stable frequency for these units.  Hope this helps @Tmerlo.

**Comment by michelem09** [comment]
Thanks for feedback @Raginglikeaboss I'm going to close this. Feel free to re-open.
