### ISSUE TITLE
minera not designed to load on external networks?

### ISSUE THREAD

**Issue by jstefanop** [getminera/minera#175]
Hey so internally minera works fine, but as soon as I try and access it from an external network, seems like everything is broken. Only a text based login screen loads very slowly, and when putting in password it redirects to internal IP address. 

I redirect external traffic from an external port to internal minera IP with NAT Loopback. This works fine for exposing antminers admin page externally, but minera does not seem to like it.

**Comment by michelem09** [comment]
I know this issue, but I still have't the time to look at it. The PHP framework doesn't print the correct URL for static files (js, css, etc...) it continues to use the LAN ip instead using the public one.
Hope to put my hands on soon.

**Comment by michelem09** [comment]
If you are a little skilled, you could try this change:

Edit file `/var/www/minera/application/config/config.php`

Look at the line `$base_url = ''` and change it with `$base_url = 'http://'.$_SERVER['HTTP_HOST']`

Then try

**Comment by michelem09** [comment]
This was definitely fixed, just do a pull:

```
cd /var/www/minera
git pull
```
