### ISSUE TITLE
Is it for RPI3? Will it show current hash rate if hashes accpeted or not? because cpu multi miner won't show

### ISSUE THREAD

**Issue by Coinizy1** [getminera/minera#176]
Hey, Still can't find the answer it will be very helpful if you just answer my two questions.
I am using Multi Cpu Miner on my RPI3 but can't see any hash rate until its get accepted why is that can i see it somehow?
I want to install this Minera on my RPI3 is it possible even if I get very very low hashrate (but it shows all time)  this is just for study purpose?
thanks

**Comment by michelem09** [comment]
Can you point me to the github repo of Multi Cpu Miner? Probably it isn't compatible with Minera web interface.
For RPI3 yes it works on it but i don't know if any cpu miner can be compatible with the web interface.
Web interface can get stats only from CPUminer built for Scrypt (built-in in Minera) or almost any Cgminer/Bfgminer fork.

**Comment by Coinizy1** [comment]
Hi, I used this on my PI3, it works fine but the only issue is its only shows Hash rate if the share is accepted.
https://github.com/tpruvot/cpuminer-multi
Did you tried this minera on PI3? can you give me any screen shot from web or your cli while it is running?
thanks

**Comment by Coinizy1** [comment]
Can i solo mine XMR from this Minera ?
and once i install it on RPI3 will it show me my hashrate ?
thanks

**Comment by michelem09** [comment]
That miner has different way to get stats so you can view only some info and not all.

No Monero is not supported.
