### ISSUE TITLE
5 Gridseed G-Blades give this error

### ISSUE THREAD

**Issue by DaveKoz** [getminera/minera#177]
Severity: Notice

Message: json_decode(): integer overflow detected

Filename: models/util_model.php

Line Number: 1131

Th UI just spins ver 0.8.0
I can never see any charts,
it worked find with 3 G Blades but when I added two more the UI is locked and unusable 
![2017-09-21_22-15-16](https://user-images.githubusercontent.com/1183431/30728018-b5415336-9f1a-11e7-8c4b-0062832ce5b0.png)
This area looks jacked

**Comment by michelem09** [comment]
That's only a notice I don't think it's the problem.
Are you using latest 0.8.0?

**Comment by hdzl** [comment]
Same problem here. Running v0.8.0 with ASIC USB sticks

/var/log/minera/
`Severity: Notice  --> json_decode(): integer overflow detected /var/www/minera/application/models/util_model.php 194`

From my opinion freezes the whole system afterwards ...

**Comment by michelem09** [comment]
That's only a notice and has nothing to do with your Bades, but if you don't trust me, trust the code, I just updated it to remove the notice.
Pull the code an see you will still have the same problems without the notice.

```
cd /var/www/minera
git pull
```

**Comment by michelem09** [comment]
Please give a try with `0.8.1`
