### ISSUE TITLE
Manual install of the version 0.8

### ISSUE THREAD

**Issue by RFHarwood** [getminera/minera#178]
SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@raspberrypi:~ $ sudo curl -o- https://raw.githubusercontent.com/getminera/minera/master/install_minera_ubuntu.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   620  100   620    0     0   3902      0 --:--:-- --:--:-- --:--:--  3924
-----
Installing Minera in /var/www
-----

Cloning into 'minera'...
remote: Counting objects: 7860, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 7860 (delta 1), reused 5 (delta 1), pack-reused 7843
Receiving objects: 100% (7860/7860), 78.87 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (3661/3661), done.
Checking connectivity... done.
Checking out files: 100% (3819/3819), done.
bash: line 21: ./install_minera.sh: Permission denied
pi@raspberrypi:~ $ ^C
pi@raspberrypi:~ $

**Comment by michelem09** [comment]
Why did you use the manual install in a Raspberry? It's simpler to use the image file https://getminera.com/download/latest

Then as workaround for that specific problem just do:

```
cd /var/www/minera
sudo ./install_minera.sh
```

**Comment by RFHarwood** [comment]
I had a problem with the image and I was trying something else to determine
if it was the image that was hanging the Pi or Minera.

**Comment by michelem09** [comment]
What kind of problem with the image?

**Comment by RFHarwood** [comment]
Hangs on boot during the "rainbow"

**Comment by michelem09** [comment]
I will give a look at it. Did you installed it manually?

**Comment by RFHarwood** [comment]
No it stopped with the access denied.

The image problem may not be on your side. I am having several problems
since the recent Windows update. I may try to roll it back.

**Comment by michelem09** [comment]
I updated the code could try the manual again?

`sudo curl -o- https://raw.githubusercontent.com/getminera/minera/master/install_minera_ubuntu.sh | sudo bash`

For the image file, try also to download it again because I changed the latest one several times.

https://getminera.com/download/latest

**Comment by RFHarwood** [comment]
I won't be able to till Monday when I get back from EVE Vegas.

**Comment by michelem09** [comment]
No problem thanks for your time.

**Comment by RFHarwood** [comment]
I am now back home. I downloaded after backing out the Windows Update. It
booted, but we got :"Severity: Notice

Message: json_decode(): integer overflow detected

Filename: models/util_model.php

Line Number: 1131" on all of my machines after the Minera update.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by michelem09** [comment]
Ref #183

**Comment by RFHarwood** [comment]
Figured out a previous issue, it wasn't your software exactly it was how it
interacted with my Chrome, AutoFill, and possibly LastPass.  Basically the
AutoFil was repeating the first pool to all the fields below it and the new
pool field.  So good news the field names confused AutoFil, so it really is
not a code issue, kind of.

After I did a clean install of Minera I apparently lost my ad free from the
Bitcoin payment.  I assume you need the SystemID, Minera ID zjuzzdimwyng

**Comment by michelem09** [comment]
Good! Thanks for feedback, for Minera Ads-free please write me to support@getminera.com and include the email you used to purchase the ads-free.
