### ISSUE TITLE
Paid Ad free disappears after turning browser mining on and off

### ISSUE THREAD

**Issue by cbrightly** [getminera/minera#179]
I wanted to try the browser mining on my phone, which is implemented in the remove ads feature. Previously I had paid to be ad free however when I stop CPU mining the ads return and will not go away. How do I return to ad free status since I have paid?

**Comment by michelem09** [comment]
Please write to support@getminera.com with your old Minera ID and your new Minera ID so I can switch it.

**Comment by cbrightly** [comment]
Strangely the issue seem to resolve itself about five minutes later

**Comment by michelem09** [comment]
Very good, only a temporary sync issue.
