### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by per-gustafsson** [getminera/minera#180]
Tried to build with current dockerfile, and recived tons of errors such as 

- Need to change  php5  to  php7.0

- NPM has no candidates

- Unable to locate package libblkmaker-0.1-dev

E: Unable to locate package libblkmaker-0.1-dev
E: Couldn't find any package by glob 'libblkmaker-0.1-dev'
E: Couldn't find any package by regex 'libblkmaker-0.1-dev'
START Minera Install script

Install extra packages 

E: Unable to locate package libblkmaker-0.1-dev
E: Couldn't find any package by glob 'libblkmaker-0.1-dev'
E: Couldn't find any package by regex 'libblkmaker-0.1-dev'

Copying Lighttpd conf

ln: failed to create symbolic link '/etc/lighttpd/conf-enabled/10-fastcgi.conf': File exists
Duplicate array-key '.php'
2017-10-13 08:23:18: (configfile.c.1154) source: /etc/lighttpd/conf-enabled/15-php-fpm.conf line: 10 pos: 1 parser failed somehow near here: (EOL) 
2017-10-13 08:23:18: (configfile.c.1154) source: /usr/share/lighttpd/include-conf-enabled.pl line: 4 pos: 1 parser failed somehow near here: (EOL) 
2017-10-13 08:23:18: (configfile.c.1154) source: /etc/lighttpd/lighttpd.conf line: 73 pos: 1 parser failed somehow near here: (EOL) 

Adding Minera logrotate
rsyslog: unrecognized service
Adding default startup settings to redis
/bin/bash: line 53: redis-cli: command not found

Adding minera startup command to rc.local
chmod: cannot access '/etc/rc.local': No such file or directory
sed: can't read /etc/rc.local: No such file or directory
Adding cron file in /etc/cron.d

Configuring shellinabox
shellinabox: unrecognized service
Copying cg/bfgminer udev rules

cp: cannot create regular file '/etc/udev/rules.d/': Not a directory
cp: cannot create regular file '/etc/udev/rules.d/': Not a directory
udev: unrecognized service
Generating unique SSH keys

rm: cannot remove '/etc/ssh/ssh_host_*': No such file or directory
dpkg-query: package 'openssh-server' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: openssh-server is not installed
ssh: unrecognized service
Building miners, this will take loooooooot of time in a low resource system, I strongly suggest you to take a beer (better two) and relax a while. Your Minera will be ready after this.

all: /var/www/minera/build_miner.sh: Permission denied
DONE! Minera is ready!

**Comment by michelem09** [comment]
Docker wasn't updated for the new release of Minera and I will remove it completely soon.
Please use the image file or the manual installation.

https://github.com/getminera/minera/wiki/Getting-started#standard-install
