### ISSUE TITLE
Network Miner - Scanned and added, shows as online then offline on main dashboard

### ISSUE THREAD

**Issue by mattbze** [getminera/minera#182]
Network Miner - Scanned and added, shows as online then offline on main dashboard

Hi, this software is really good I will be donating if I can configuring it for my needs. However I have ran into an issue where the web interface succesfully scans my antminer and shows as online. I then go back to the dashboard and it shows as offline. 

Here is my cgminer.conf api extract.

"api-listen" : true,
"api-network" : true,
"api-groups" : "A:stats:pools:devs:summary:version",
"api-allow" : "A:0/0,W:192.168.1.232",
"bitmain-use-vil" : true,
"bitmain-freq" : "444"

Please can you advise if thats incorrect for Minera and if its not what other diagnostic steps I should take

**Comment by michelem09** [comment]
Hello, I need some info: what kind of Antminer are? And what is the minera IP?

**Comment by mattbze** [comment]
Hi,

Its an Antminer L3+ and the local ip is 192.168.1.232

Thanks

**Comment by michelem09** [comment]
L3/+ is not compatible with Minera, it just shows you is online but it can't work because I think (but I can't test it) it has a completely different way to expose the API info.
I'm sorry but I can't help on this and the same is for S9. For Minera they are simply incompatibles.

**Comment by jhicken** [comment]
Is this on the list of things to do?

**Comment by michelem09** [comment]
Don't know because I need to put my hands on a L3 and I haven't one neither I'd like to buy one, so if it happens I will do something or nothing.

**Comment by mattbze** [comment]
I would be happy to assist you with mine if you would like.

**Comment by michelem09** [comment]
@mattbze are you able to let me access into your L3 by SSH? I only need to look around if it's possible to get stats from it (remotely) then if I need to change something I'll ask before.

**Comment by mattbze** [comment]
Yeah sure thats fine im just in work this week though. Which timezone are you on? I can set aside some time Friday night / Saturday or Sunday.

**Comment by michelem09** [comment]
I'm in Italy, I'd need port 22 (ssh) and port 4028 (cgminer) open to public or limited to my public IP.
Weekend could be good to me too. Thanks.

**Comment by mattbze** [comment]
Hi, should be fine I just need to get the required routes in place for you. Can you private message me your public IP and ill give you access.  Im in the UK so we match up with time zones.

**Comment by michelem09** [comment]
Unfortunately I haven't a fixed IP here so if you kindly could write me a message when you are ready I will give the current IP. Please write to support@getminera.com when you can.

**Comment by C-Fu** [comment]
Good day,

I just found out that another project claims to successfully able to monitor L3+, D3, S7 and S9.
https://github.com/anselal/antminer-monitor

I just sent my ASICs away, so can't really test that project. But while I have the coding skills of a baby, I can only imagine that the project might have some useful stuff for you to use. Cheers and keep up the good work!

**Comment by xslugx** [comment]
I am also willing to help with access to Miners if it is still needed.

**Comment by michelem09** [comment]
Hey folks! Minera now supports L3+! Please follow this thread to know all about it: https://bitcointalk.org/index.php?topic=596620.msg25373186#msg25373186

Tester needed! (Scan the network is still not working due to the small timeout I set, you should increase it to use the scan, or wait for my official release)

**Comment by mattbze** [comment]
Hi Sorry I never came back to you. 

I initially forgot about our agreement and then my son has been in hospital for a short while so iv had other things on my mind.

Anyway thats all over and done with now so im happy to test it and give it a go.

Sorry again.

KR
Matt

**Comment by michelem09** [comment]
No problem at all Matt! Take care of your son, I hope he is good now.

**Comment by C-Fu** [comment]
I have a D3 that I'm willing to let you guys test it out. Lemme know when

**Comment by michelem09** [comment]
@C-Fu hey thanks! But did you try the latest commit I did? I think with the L3+ changes also D3 should work.

Could you try it?

Just get Minera 0.8.1 and then update its code with following commands:

```
cd /var/www/minera
sudo git fetch --all && sudo git reset --hard origin/master
```

Or if you prefer, I'd need to reach port 4028 of your D3 to test it.

**Comment by michelem09** [comment]
Minera v0.9.0 is ready! Update for S9 / L3+ / D3 support!

**Comment by xslugx** [comment]
Thanks @michelem09 for your work!

**Comment by michelem09** [comment]
Thanks for all your support!

**Comment by C-Fu** [comment]
I tried the git fetch and git reset command, here's the error:

Fetching origin
error: inflate: data stream error (invalid code lengths set)
error: failed to read object 1717404114b22976837a1d5ec02775c0100de1fa at
offset 170974 from .git/objects/pack/pack-5afd9cb9b30ca0b156056e281b76c3
c2485dbc8b.pack
fatal: packed object 1717404114b22976837a1d5ec02775c0100de1fa (stored in
.git/objects/pack/pack-5afd9cb9b30ca0b156056e281b76c3c2485dbc8b.pack) is
corrupt

Minera is running while doing this btw. Is it on my side or yours? noob here

**Comment by michelem09** [comment]
You have corrupted files your side:

> fatal: packed object 1717404114b22976837a1d5ec02775c0100de1fa (stored in
> .git/objects/pack/pack-5afd9cb9b30ca0b156056e281b76c3c2485dbc8b.pack) is
> corrupt

You could move the current minera folder and redo a git clone.

```
cd /var/www
mv minera minera.OLD
git clone https://github.com/getminera/minera
```

This should fix the problem, but you have to have a recent Minera (>= 0.8.0), otherwise don't waste your time (0.7.0 isn't upgradable) and get the new image file to start from scratch.
