### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by ChristopherVermeer** [getminera/minera#183]
This is from the stat page, the dashboard is not working just spins in infinite circles. 

`<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  json_decode(): integer overflow detected</p>
<p>Filename: models/util_model.php</p>
<p>Line Number: 194</p>

</div>{"start_time":1508730897,"devices":{"GSD0":{"temperature":0,"frequency":838,"accepted":4,"rejected":0,"hw_errors":7,"shares":91841,"hashrate":6530860000,"last_share":1508731317,"serial":"ttyACM2"},"GSD1":{"temperature":0,"frequency":838,"accepted":7,"rejected":0,"hw_errors":5,"shares":90194,"hashrate":6383740000,"last_share":1508731362,"serial":"ttyACM4"}},"totals":{"temperature":false,"frequency":838,"accepted":11,"rejected":0,"hw_errors":12,"shares":182035,"hashrate":12914600000,"last_share":1508731429},"pool":{"hashrate":12755729934,"url":"stratum+tcp:\` 

What recommendations do you have for this issue? 

`Chris

**Comment by michelem09** [comment]
I think you still have PHP5 instead PHP7, please I need the Minera version and the output of this command:

`sudo dpkg -l | grep php`

**Comment by michelem09** [comment]
This is fixed with latest image. You need PHP7.0 or download the latest image.
