### ISSUE TITLE
Trying to connect to AntMiner L3+, able to scan, but went offline after saving

### ISSUE THREAD

**Issue by C-Fu** [getminera/minera#184]
I'm trying to connect to my L3+ machines, just for monitoring purpose (temp, hashrate, etc) and not for remotely managing the miners (for now).

If I click on settings>network miners, it shows that those machines are online with the algorithm somehow set to SHA-256 (Scrypt is the correct one, and the dropdown list only lists Scrypt and SHA-256). Changing these to either one doesn't seem to do anything. Scanning managed to get the default port.

Click on save or Save & Restart Miner, or going to Dashboard manually will keep showing that those devices are offline. Is there a step that I'm missing?

Don't think this matters, but installed manually on berryboot's Raspbian. Also, I am able to monitor the miners via Window's AwesomeMiner, also in the same network.

**Comment by michelem09** [comment]
Dup of #182
