### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by JoeDC696** [getminera/minera#185]
Hi,

I prefer to manage minera on the raspberry pi with mouse, keyboard and TV connected.
I'm having problem with the manual install of minera.

After following instructions found at https://github.com/getminera/minera/wiki/Getting-started    I pointed my browser to http://192.168.1.100/minera/
ip address of my rasp pi is 192.168.1.100
and error message came out as ,
**This site can’t be reached**
**192.168.1.100 refused to connect.**

These are the codes I copied and executed:

**curl -o- https://raw.githubusercontent.com/michelem09/minera/master/install_minera_ubuntu.sh | sudo bash**

> I suspected some anomaly in the result here: 
Now using node v6.11.5 (npm v3.10.10)
cp: cannot create regular file '/etc/supervisor/conf.d/': No such file or directory
npm WARN minera@1.0.0 No description
npm WARN minera@1.0.0 No repository field.
Failed to restart supervisor.service: Unit supervisor.service not found.
Generating unique SSH
: Is this an issue ?

**sudo apt-get install -y redis-server git screen php7.0-cli php7.0-curl**

**cd /var/www**

**sudo git clone https://github.com/michelem09/minera**

> result is 
fatal: destination path 'minera' already exists and is not an empty directory.

**cd minera**

**sudo ./install_minera.sh**

> Again, I noticed the anomaly:
cp: cannot create regular file '/etc/supervisor/conf.d/': No such file or directory
npm WARN minera@1.0.0 No description
npm WARN minera@1.0.0 No repository field.
Failed to restart supervisor.service: Unit supervisor.service not found.

Is there something I had to do before running the above codes ?
Could you suggest anything I could test or try out

**Comment by michelem09** [comment]
It seems you haven't a web server ready on the RPI. My suggestion is to start from scratch downloading the Minera image for RPI and using that instead the manual install you did. 
https://getminera.com/download/latest

**Comment by JoeDC696** [comment]
Ok.

But after the image install, how can I be able to run the minera on the RPI
with it the connected mouse, keyboard & TV.  What are the steps. Because
I'm stuck up with the CLI after reboot.

What is the command to run the browser.  I'm newbie in linux & I find it
very challenging.

Thanks for your reply.

On Nov 2, 2017 12:16 AM, "Michele Marcucci" <notifications@github.com>
wrote:

It seems you haven't a web server ready on the RPI. My suggestion is to
start from scratch downloading the Minera image for RPI and using that
instead the manual install you did.
https://getminera.com/download/latest

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/getminera/minera/issues/185#issuecomment-341155863>,
or mute
the thread

**Comment by michelem09** [comment]
You have to use your PC browser pointed to the rpi IP. Minera hasn't
desktop installed.
Il giorno mer 1 nov 2017 alle 19:25 JoeDC696 <notifications@github.com> ha
scritto:

**Comment by JoeDC696** [comment]
However, in my first attempt, when I just opened my RPI and installed it with Raspbian OS and next, installed the minera, I did successfully and was able to point my browser to the dashboard with the TV, mouse & keyboard connected to the RPI.  I did not use any PC pointing to the RPI.

But due to hardware problem, probably the RAM of the RPI is defective and system freezes after several hours,  I was inclined to reset and re install the Raspbian OS and used another RPI bought from other supplier.  I keep on trying to run the minera in that previous condition.  I hope it would work out again.  

I could not recall the steps I've gone through to achieve that condition.

Do you have any idea why it worked ?  Is there any other way to make it work that way ?

Thanks again for your reply.

**Comment by michelem09** [comment]
Minera image has the desktop disabled because it's not intended for this use, as you said, Rpi isn't good for desktop tasks.
So you have to start from Raspbian OS and then run the Minera manual install:

`curl -o- https://raw.githubusercontent.com/michelem09/minera/master/install_minera_ubuntu.sh | sudo bash`

But this is a skilled (expert) mode and you should know what you are doing.
