### ISSUE TITLE
Rebooting loop.

### ISSUE THREAD

**Issue by JoeDC696** [getminera/minera#188]
One of the asic device was idle so I tried to reboot the system from the dashboard.  Since then, It doesn't seem to stop rebooting & rebooting in a loop.

I got the screenshot of the error message attached here.

![errmsg01](https://user-images.githubusercontent.com/33275659/32839667-19f9cf32-ca50-11e7-921c-5b6ff56f3710.jpg)

**Comment by michelem09** [comment]
Related to this #143
