### ISSUE TITLE
Antpool pool information

### ISSUE THREAD

**Issue by maco1717** [getminera/minera#196]
Hi,

A really good feature would be to get the data from the antpool API like this you dont only have the hashrate from the miner but from the pool and can get more accurate estimates of what the miners are doing...

**Comment by michelem09** [comment]
You just have some data from Antminers, about miner and about pools, what kind of data do you mean?

**Comment by maco1717** [comment]
so when mining on antpool you get "your hash rate" (the hash rate of the miner(s)) also get the hashrate of a worker... I can get you a screenshot.
