### ISSUE TITLE
Logs are not collected and charts are not pictured

### ISSUE THREAD

**Issue by ant1freeze** [getminera/minera#198]
I have some Antmain L3+ in the same local network with server of Minera.
I can see its hashrate, temp, frequency etc, but there is no graph in the field of chart (for example, Local Hashrate History). Of course I was waiting more than 10 min, but i see only straight line at 0 Mh/s instead near 500 Mh/s.
Also i try to start miner realtime log, but it's clean.
![miner](https://user-images.githubusercontent.com/1762712/34250367-b5223f58-e64d-11e7-9d5e-164545bad8e8.png)
![chart](https://user-images.githubusercontent.com/1762712/34250369-b5509736-e64d-11e7-9d41-bbfce2d2eb50.png)
![log](https://user-images.githubusercontent.com/1762712/34250371-b59511ea-e64d-11e7-97da-9fae310e10cf.png)

**Comment by michelem09** [comment]
Charts are available only for local miners not networked ones.
