### ISSUE TITLE
Rasberry Pi Crashes

### ISSUE THREAD

**Issue by jaydubbb** [getminera/minera#200]
Not sure if its Minera that's crashing or if the Mining USB stick is crashing, but the issue i'm having is it crashing quite often now and i would not be able to log on through an ip address over the browser.  I would have to reboot the rasberry pi for it to work again.

**Comment by cmrockwell** [comment]
I might have the same issue. Using RPI3. I left a terminal open and saw this when it crashed..


Message from syslogd@minera at Dec 24 00:53:47 ...
 kernel:[ 1827.046304] Internal error: Oops: 5 [#1] SMP ARM

Message from syslogd@minera at Dec 24 00:53:47 ...
 kernel:[ 1827.113651] Process wicd (pid: 823, stack limit = 0xb3972210)

Message from syslogd@minera at Dec 24 00:53:47 ...
 kernel:[ 1827.117810] Stack: (0xb3973e98 to 0xb3974000)

Message from syslogd@minera at Dec 24 00:53:47 ...
 kernel:[ 1827.121796] 3e80:                                                       801b3704 8028bcc8

Message from syslogd@minera at Dec 24 00:53:47 ...
 kernel:[ 1827.129958] 3ea0: b3973ecc 00006443 ab97a080 a0000013 00000160 80c0c7a8 ab97a000 80c1efe8
...

**Comment by michelem09** [comment]
Do you have wireless active?

**Comment by cmrockwell** [comment]
Thanks for responding. This is a really great project. I believe wifi is enabled. ifconfig showed wlan0, but the connection is by ethernet. Would you recommend disabling wifi? 

if so, I found these options...
https://www.raspberrypi.org/documentation/configuration/config-txt/README.md
https://askubuntu.com/questions/762198/16-04-lts-wifi-connection-issues

sudo iwconfig wlan0 txpower off

#added to /boot/config.txt
#disabled wifi
dtoverlay=pi3-disable-wifi

**Comment by jaydubbb** [comment]
Hmmmm seems to be working now.  I switched to another USB hub and I think it might be a power issue.  

I have another question though.  When logging into minera terminal what is the default login id?

**Comment by michelem09** [comment]
If you don't use wifi yes disable it, because this line is from `wicd` that's something related to wifi:

> kernel:[1827.113651] Process wicd (pid: 823, stack limit = 0xb3972210)

Default login to minera is:

> user: minera
> pass: minera

**Comment by jaydubbb** [comment]
It's so weird.  minera/minera isn't working for me.  It did before when I set the whole thing up.  Is there any way to locate the login id?  Thanks!

**Comment by michelem09** [comment]
Did you install it manually? Can you login with another user?

**Comment by jaydubbb** [comment]
Hmmm don't think I ever set up other id's

**Comment by michelem09** [comment]
I mean Minera, how did you install MInera? If default user doesn't work you didn't use the official image.

**Comment by jaydubbb** [comment]
hmmmm i believe i cloned the image from here.  is there any way i can look it up and see what the admin log might be?

**Comment by michelem09** [comment]
If you cloned from here without doing the manual install you haven't the minera user set.
If you have too much problems, please restart from scratch downloading the latest RPI image  https://getminera.com/download/latest

**Comment by jaydubbb** [comment]
Sounds good!  I will do that.  Thank you so much for the support!
