### ISSUE TITLE
Network worker scan doesn't time-out

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [getminera/minera#205]
When network scanning for remote workers the scan never times out on failure to find workers (because, for instance, my remote workers are on a different network).

Reloading the page forces stop, but it also loses any un-saved work.

Add a time-out to the network scan, please. If it can't find anything in 30-60 seconds, let it stop.

**Comment by michelem09** [comment]
Good point, I'll add something like this but not so soon.

**Comment by michelem09** [comment]
on next release you can specify the network to be scanned so you can scan only small portions without doing the whole one (if it's huge like 10.0.0.0/8)
