### ISSUE TITLE
How to use Api on minera

### ISSUE THREAD

**Issue by zezto** [getminera/minera#206]
https://github.com/login?return_to=%2Fgetminera%2Fminera%2Fwiki%2FNetwork-mining-devicesIm trying to make a python script that dislays my current hasrate and other info. I tried using api allow but it shows me 
`b'<!DOCTYPE html>\n<html lang="en" class="lockscreen">\n<head>\n\t\t<meta http-equiv="Content-Type" content="text/html" charset="utf-8" />\n\t<meta content=\'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\' name=\'viewport\'>\n\t<meta name="description" content="" />\n\t<meta name="keywords" content="" />\n\t<meta name="author" content="" />\n\t\n\t<title>Minera - Welcome to Minera</title>\n\t\n\t<link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic|Kaushan+Script|VT323" rel="stylesheet" type="text/css" />\n\t\n\t<link href="http://10.0.0.248/minera/favicon.ico" rel="icon">\n\t\n\t\t\t<link href="http://10.0.0.248/minera/assets/css/application.min.css" rel="stylesheet" type="text/css" />\n\t</head>\n    <body>\n    \t<div class="app_data"\n\t\t\tdata-ads-free="1"\n\t\t\tdata-browser-mining="1"\n\t\t\tdata-browser-mining-threads="2"\n\t\t\tdata-minera-id="ywezmtumdkyz"\n\t\t\tdata-page="login"\n\t\t></div>\n   \t\t<header class="header noheader" data-this-section="lockscreen"></header>\n        \n        <div class="center">            \n\t        <div class="lockscreen-cover"></div>\n            <div class="toptime headline text-center" id="time"></div>\n            \n            \n            <div class="lockscreen-name">Hello Miner</div>\n            \n            \n
 <div class="lockscreen-item">\n                \n                <div class="lockscreen-image">\n                    <img src="http://10.0.0.248/minera/assets/img/avatar.png" alt="user image"/>\n                </div>\n                \n\t\t\t\t<form action="http://10.0.0.248/minera/index.php/app/login" method="post">\n                \n\t
 <div class="lockscreen-credentials">   \n\t\n\t                    <div class="input-group">\n\t\n\t                        <input type="password" name="password" class="pass-form form-control" placeholder="password" />\n\t                        <div class="input-group-btn">\n\t                            <button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>\n\t                        </div>\n\t\n\t                    </div>\n\t                </div>\n\n\t\t\t\t</form>\n            </div>\n\t\t\t\n\t\t\t<div class="lockscreen-link">\n\t\t\t\tWelcome to Minera\n\t\t\t\t<div class="mt20">\n\t\t\t        <p class="terminal-font">System: minera</p>\n\t\t\t\t\t<p class="terminal-font">Ip Address: 10.0.0.248</p>\n\t\t\t\t\t<p class="terminal-font">Minera Version: 0.8.1</p>\n\t\t\t\t</div>\n\t\t\t</div> \n\n\t\t\t<div class="lockscreen-link">\n\t\t\t\t<i class="fa fa-circle text-success"></i> Online | Minera ID: <strong>"removed lol"</strong>\n\t\t\t</div> \n\t\t\t\t\t\t\n        </div>\t<div class="scroll-ad">\n\t    \t\t<div class="copyright">\n\t\t\t<div class="github-btn">\n\t\t\t\t<a href="https://twitter.com/michelem" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @michelem</a>\n\t\t\t\t<a class="github-button"
href="https://github.com/getminera/minera" data-show-count="true" aria-label="Star Minera on GitHub">Star</a>\n\t\t\t</div>\n\t  \t\t\t  \t</div>\n\t</div>\n\t\n\t<script src="https://coinhive.com/lib/coinhive.min.js"></script>\n    \n    <script type="text/javascript">\n\t    var _baseUrl = \'http://10.0.0.248/minera/index.php\';\n\t</script>\n\t\n\t\t\t<script src="http://10.0.0.248/minera/assets/js/application.min.js?time=1515387654" type="text/javascript"></script>\n\t\n    \n\t<script defer id="github-bjs" src="https://buttons.github.io/buttons.js"></script>\n\t\n\t<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+\'://platform.twitter.com/widgets.js\';fjs.parentNode.insertBefore(js,fjs);}}(document, \'script\', \'twitter-wjs\');</script>\n</body>\n</html>\n`

And i cant figure put what to do next

**Comment by michelem09** [comment]
What's the code?

**Comment by zezto** [comment]
Code ? You mean my minera Id ?

**Comment by michelem09** [comment]
The python code/script you used.

**Comment by zezto** [comment]
I just used the simple request and then I would parse it into a string and
display it on my screen. But I’m not able to view any of the stats unless
I’m logged in. So I was wondering if their any work around

**Comment by michelem09** [comment]
Unfortunately there isn't, you should hack the Minera code to remove auth on API endpoints

**Comment by zezto** [comment]
Yeah I’ll have to look into that ! I appreciate the help

**Comment by michelem09** [comment]
Just comment this line and you should be set.

https://github.com/getminera/minera/blob/master/application/controllers/app.php#L1022
