### ISSUE TITLE
Difficult Setup for Network Miner on Antminer S9

### ISSUE THREAD

**Issue by jpbrewer** [getminera/minera#207]
I have 21 Antminer S9s and found that setting multiple up was troublesome.  Yes, the autodetect does not work (a verified bug, under another ticket).  If I type in the IP addresses and save, it does say they are ONLINE in the network miner setup area, but the sometimes the Dashboard leaves them OFFLINE with no data.  Some come online eventually, others never do.  I delete OFFLINE ones and redo until I get it to work.  I have yet to get them all to report on the dashboard.

Also, would be helpful if you give a hint that that port for the S9 is 4028.  I eventually figured it out.

**Comment by michelem09** [comment]
v0.9.1 have a better network scanner (still not bug free), try it.
