### ISSUE TITLE
Antminer V9

### ISSUE THREAD

**Issue by clintonm9** [getminera/minera#214]
Would this software also work for the new Antminer V9 miner?

Thanks

**Comment by evilqubit** [comment]
actually i m still trying to make it work on my network miners there is a lot of bugs ajax loading stuck sometime miners appears sometimes not ...

**Comment by evilqubit** [comment]
actually i m still trying to make it work on my network miners there is a lot of bugs ajax loading stuck sometime miners appears sometimes not ...

**Comment by michelem09** [comment]
@clintonm9 hard to say they are just released I haven't any feedbacks.
@evilqubit what version of Minera do you use? You need 0.9.0

**Comment by clintonm9** [comment]
I have an order of 25 coming in. I would be happy to test it if you all want to support it.

**Comment by michelem09** [comment]
@clintonm9 thank you very much, BTW I think V9 will have the same Cgminer with same API so probably it will work as is, but please let me know when you have some in your hands, much appreciate.

**Comment by clintonm9** [comment]
@michelem09 I got the V9s in today. I am newer to this model and noticed that there is no SD card, only an SD card slot. I flashed a new SD card with the Minera image, plugged into the SD slot and it seems the miner doesn't ever spin up or grab an IP. I am assuming it is using DHCP. 

Any ideas?

**Comment by michelem09** [comment]
Never used Minera as controller for Antminer. I always used it in a Raspberry and then setup the Antminer as network miner in Minera settings.

**Comment by clintonm9** [comment]
I used a Raspberry and connected if via Network. It shows online, but I do not show any hash rates or temp, etc.

Here is part of the config from the miner:
```
"api-listen" : true,
"api-network" : true,
"api-groups" : "A:stats:pools:devs:summary:version",
"api-allow" : "A:0/0,W:*",
"bitmain-use-vil" : true,
"bitmain-freq" : "600"
}
```

**Comment by michelem09** [comment]
That should be good, but unfortunately I cannot tell you more, I'd need to play with it with my hands on but I'm not available this period because I'm abroad for a while.

**Comment by michelem09** [comment]
v0.9.1 should support it
