### ISSUE TITLE
Manual remove

### ISSUE THREAD

**Issue by git4silver** [getminera/minera#216]
Hi,
How can I remove minera form Raspberry Pi 3 ?
Can somebody share with me few commands to do that ?
Thanks!

**Comment by michelem09** [comment]
Well, removing everything it's a little bit hard, but I think this could be sufficient:

```
sudo rm -rf /var/www/minera
sudo rm /etc/cron.d/minera
sudo apt remove redis-server
sudo apt remove supervisor
```

I don't suggest to remove also the `minera` user because it's the only one that can access it.

**Comment by git4silver** [comment]
Thanks @michelem09 ,
Do you knew what is redirecting me on localhost to localhost/minera ?
So I am still missing something...

**Comment by michelem09** [comment]
Ah right it's the lighttpd web server you should remove it or change the
config file.
Il giorno dom 18 feb 2018 alle 21:33 git4silver <notifications@github.com>
ha scritto:
