### ISSUE TITLE
Is there a API for gettings easy data from the Miner?

### ISSUE THREAD

**Issue by byEliteHacks** [getminera/minera#218]
I woud like to get simple infortmation off my Miners like Status /ON/OFF hashrate and temp is there like a json api or something included?

**Comment by michelem09** [comment]
Yes there is but it's under authentication you should remove a line of code to be able to use it, look here https://github.com/getminera/minera/issues/206#issuecomment-367763715

Then url will be: `http://<ip>/minera/index.php/app/api?command=miner_stats` and `http://<ip>/minera/index.php/app/api?command=stats`
