### ISSUE TITLE
Support for additional miners

### ISSUE THREAD

**Issue by ravensorb** [getminera/minera#221]
Any thoughts on extending support for other miners (Eth, Claymore, etc)?

**Comment by michelem09** [comment]
No also because Minera was born and still intended for Raspberry use where you can't mine with GPU, so it doesn't make sense.
Sorry.

**Comment by ravensorb** [comment]
Not sure I follow.  Wouldn't it be a matter of accessing this tools monitoring APIs (ex: claymore has a json-rpc based api)

**Comment by michelem09** [comment]
Not so easy, you have also to manage the start/stop and the configurations. Furthermore you should also prepare the system with all the drivers needed by the various GPU cards. It should be completely different from the current Minera.

**Comment by ravensorb** [comment]
Agreed and the claymore api allows for stats per card, as well as ability to start/stop miner or individual cards if needed.  Or is there more that is needed?

**Comment by ravensorb** [comment]
Ahh, ok I understand now.  You are correct in that regards, you need to update a file and then you can trigger a "restart" with the API.

**Comment by michelem09** [comment]
Correct.
