### ISSUE TITLE
Minera add an Antminer A3 Blake2B

### ISSUE THREAD

**Issue by CirrusThink** [getminera/minera#223]
Does MINERA support blake2B for network miners ?
When adding a network miner I don't have an option for BLAKE2B algorithm
Trying to add an Antminer A3

**Comment by CirrusThink** [comment]
When adding the Antminer A3 network miner, it sees the miners with a green label but when going back to dashboard they are not appearing as online. Do we still need to open the conf file locally on each miner in order to accept the MINERA request calls ? Example "api_allow" . I followed the instructions for S9, I am using 0.90.0

**Comment by michelem09** [comment]
I never tried A3 but it should equal to all the other miners from Bitmain so yes you will require the api-allow options set, what's your config?

**Comment by CirrusThink** [comment]
Sapresti qual'e' il path delle configurazioni nell Antminer ?
Inoltre non so se hai notato ma nel pull down del network miner non c'e' una opzione per Blake2B algorithm. Nel frattempo vedo di aggiungere il allow set appena trovo il file di config o come aggiungere le info in maniera da risultare permanenti .

**Comment by michelem09** [comment]
I don't remember it and yes I know I have to update something in the code. BTW it should work selecting L3 or S9.

**Comment by CirrusThink** [comment]
When will you be able to update the code on your end to reflect the correct hash algorithm  ?
Which configuration file do you need me to cat from the A3 antminer ?
This is what I have so far from the cgminer.conf file

pool infos ...
{
"pools" : [
{
"url" : "us-east.siamining.com:3333",
"user" : "wallet & worker info",
"pass" : "123"
},
{
"url" : "us-east.siamining.com:3333",
"user" : "wallet & worker info",
"pass" : "123"
},
{
"url" : "us-east.siamining.com:3333",
"user" : "wallet & worker info",
"pass" : "123"
}
]
,
"api-listen" : true,
"api-network" : true,
"api-groups" : "A:stats:pools:devs:summary:version",
"api-allow" : "A:0/0,W:*,W:127.0.0.2,W:192.168.100.1/24",
"bitmain-use-vil" : true,
"bitmain-freq" : "675"

**Comment by CirrusThink** [comment]
The path is /config/cgminer.conf

**Comment by CirrusThink** [comment]
Restart Minera after adding info and dashboard network miner now states 
"No active pools data available." It does not seem that Minera can be configured to understand A3 at this time. Any logs that I can send your way from Mineras Dashboard ?

**Comment by CirrusThink** [comment]
Any updates ? Please advise

**Comment by michelem09** [comment]
Please refer to #236
