### ISSUE TITLE
Antminer u3

### ISSUE THREAD

**Issue by miek158** [getminera/minera#224]
Witam wszystkich ostatnio chciałem zobaczyć jak działa koparka z czystej ciekawości i zaopatrzyłem się w u3 oraz raspberry pi3 po instalacji i wielu prubach nadal cgminer nie pokazuje żadnej koparki co jest nie tak??

**Comment by michelem09** [comment]
Please speak english.

**Comment by miek158** [comment]
Hello everyone, I recently wanted to see how the excavator works out of pure curiosity and I bought the u3 and raspberry pi3 after installation and many prubach still cgminer does not show any excavator what is wrong?

**Comment by michelem09** [comment]
This is not a support forum, please post your problems here https://bitcointalk.org/index.php?topic=596620.0
