### ISSUE TITLE
Help with Moonlander and Raspberry Pi

### ISSUE THREAD

**Issue by ChrisCalzaretta** [getminera/minera#227]
i just got this
https://www.amazon.com/gp/product/B077VPCS6N/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1
I got it working on the Pi via this
https://steemit.com/raspberry/@qctechno/howto-install-futurebit-moonlander-2-usb-scrypt-miner-with-raspberrypi-3

I have minera running on the pi however i had to start it up like this
<img width="576" alt="untitled" src="https://user-images.githubusercontent.com/1654001/39960898-5936c37a-55e8-11e8-8f92-420012c05934.png">

Review image.
As far as the pool being put in to the args.. That was the only way i could get it to run inside of minera

It was kind of a pain to get it to work and it does not work 100% with Minera. I want to know if there is a better way of getting this to work.. 
it does not report any stats back to Minera. :(

**Comment by alex82361** [comment]
i just installed the bfgminer in that directory and ran it

**Comment by michelem09** [comment]
v0.9.1 have Futurebit bfgminer as custom miner built-in, you should try that.

**Comment by alex82361** [comment]
Thank you for doing this. I'll give it a try.
