### ISSUE TITLE
uninstall script

### ISSUE THREAD

**Issue by a3igner** [getminera/minera#230]
Can you please create an uninstall script or show a method on the main page how to uninstall everything related to minera?

**Comment by Illustratum** [comment]
I was wondering the same, Im manually searching around to "clean up"

Googling a "uninstall script" gave me nothing.

I just wanted to monitor my old ASIC but this Crypto world have turned into a Gold Rush with no regards of reality.

I hope it calms down and good projects prevails.

**Comment by michelem09** [comment]
This is open source project, just check the install script and with a bit of reverse engineering you got your uninstall script. If you wanna contribute then I will be very glad to add it to the code.
Thanks
