### ISSUE TITLE
How about Antminers S9i and L3++?

### ISSUE THREAD

**Issue by Navookh** [getminera/minera#231]
I just installed those models and can't view them in Minera. (S9 - Ok)
I think, they came with same API as S9 and L3, but with another type name.

What can I change in Minera for monitoring Antminer S9i and L3++?

**Comment by michelem09** [comment]
Try to paste the output of `/minera/api?command= miner_stats`

**Comment by Navookh** [comment]
Sorry, I've changed soft for those miners.

Can you try help with T9:
{"notrunning":true,"network_miners":{"Telescopium":{"config":{"ip":"192.168.88.254","port":"4028","algo":"SHA-256"}},"253":{"start_time":1532702733,"totals":{"temperature":false,"frequency":false,"accepted":2864,"rejected":2,"hw_errors":6092,"shares":0,"hashrate":0,"last_share":1533194775},"pool":{"hashrate":10427321562384,"url":"stratum+tcp:\/\/sha256.in.nicehash.com:3334","alive":true},"pools":[{"priority":0,"url":"stratum+tcp:\/\/sha256.in.nicehash.com:3334","active":true,"user":"36x6GMmgSgJ9JbB7iqLqc6xk7xMYtFVXJw.89x174","pass":false,"stats":[{"start_time":false,"accepted":2856,"rejected":2,"shares":24032,"stop_time":false,"stats_id":1}],"stats_id":1,"alive":true},{"priority":1,"url":"stratum+tcp:\/\/sha256.eu.nicehash.com:3334","active":false,"user":"36x6GMmgSgJ9JbB7iqLqc6xk7xMYtFVXJw.88x253","pass":false,"stats":[{"start_time":false,"accepted":6,"rejected":0,"shares":173,"stop_time":false,"stats_id":1}],"stats_id":1,"alive":true},{"priority":2,"url":"stratum+tcp:\/\/sha256.eu.nicehash.com:3334","active":false,"user":"36x6GMmgSgJ9JbB7iqLqc6xk7xMYtFVXJw.88x253","pass":false,"stats":[{"start_time":false,"accepted":2,"rejected":0,"shares":87,"stop_time":false,"stats_id":1}],"stats_id":1,"alive":true}],"config":{"ip":"192.168.88.253","port":"4028","algo":"SHA-256"}},"8854":{"config":{"ip":"192.168.88.54","port":"4028","algo":"SHA-256"}}},"minera_id":"mzfmnzvmyziw","miner":"cpuminer","algo":"SHA-256","sysload":[1.38,1.41,1.3],"cron":null,"sysuptime":"492206","temp":{"value":"26.80","scale":"c"},"btc_rates":null,"altcoins_rates":{"error":"true"},"avg":{"1min":[],"5min":[false],"1hour":[false],"1day":[false]},"profits":[{"symbol":"btc","coin":"bitcoin","algo":"sha256","reward":12.5,"difficulty":5949437371609.5,"blocks":534813,"networkhashps":"46157927834068360000","btcValue":1,"price":1,"coin_profitability":4.226569328154e-11,"btc_profitability":4.226569328154e-11,"timestamp":1533194764,"hashrate":1000000},{"symbol":"bch","coin":"bitcoin cash","algo":"sha256","reward":12.5,"difficulty":1605880.2960851,"blocks":599025,"networkhashps":21793162544590,"btcValue":0.099245,"price":0.099245,"coin_profitability":0.0001565852048619,"btc_profitability":1.5540298656519e-5,"timestamp":1533194764,"hashrate":1000000},{"symbol":"ltc","coin":"litecoin","algo":"scrypt","reward":25,"difficulty":10070201.868056,"blocks":1467032,"networkhashps":2.9997813657316e+14,"btcValue":0.0101206,"price":0.0101206,"coin_profitability":4.9940825107752e-5,"btc_profitability":5.0543111458551e-7,"timestamp":1533194764,"hashrate":1000000}],"livestat":true,"timestamp":1533194775}

**Comment by Navookh** [comment]
T9 also figured in Dashboard as "offline"

**Comment by michelem09** [comment]
Related to #236 
If you could show me the output of that command would be helpful

**Comment by michelem09** [comment]
v0.9.1 should support them
