### ISSUE TITLE
terminal from mineral takes me to  pi@raspberrypi$

### ISSUE THREAD

**Issue by dralibak** [getminera/minera#233]
I can't get to Minera login at the terminal.  It keep takes me to raspberry $  
can't do ssh to minera@ip address ... it says connection refused.

but I am able to go to minera directory and do stuff.  I just can't copy from another directory to inside minera as it says no permission .. 

how do I get to login of minera from terminal if I can't access it via minera web page! and why can't I?

trying to install vthoang gekko 2pac version of cgminer for custom cgminer in raspberry pi 3

**Comment by michelem09** [comment]
This is not a Minera issue, this is something related to your specific setup. Use the Minera image to install it and it will work.
