### ISSUE TITLE
Manual install URL?

### ISSUE THREAD

**Issue by FlatEarthDave** [getminera/minera#235]
This is what I get at the end of the manual install process on a Beaglebone Black Rev. C:

DONE! Minera is ready!

Open the URL: http://192.168.1.18192.168.7.2192.168.6.2/minera/

And happy mining!

**Comment by michelem09** [comment]
Does it work if you use http://<beaglebon-ip>/minera/?
That's because you don't have a standard/fresh install of Raspian I think.

**Comment by FlatEarthDave** [comment]
That does not work.

I have a fresh debian install on Beaglebone Black, not Raspberry Pi.

The image will not boot, so i have to try manual install

**Comment by michelem09** [comment]
You could try to start from this image https://www.raspberrypi.org/downloads/raspbian/
Then do the manual install again.

**Comment by FlatEarthDave** [comment]
Because I use a beagleboard, it has it’s own webserver running. I uninstalled apache2, but that didn’t work. After days of scouring the Internet, this ended up doing the trick:

systemctl disable cloud9.service
systemctl disable gateone.service
systemctl disable bonescript.service
systemctl disable bonescript.socket
systemctl disable bonescript-autorun.service
systemctl disable avahi-daemon.service
systemctl disable gdm.service
systemctl disable mpd.service

I did get it working, but it doesn’t seem to support the L3++ or Z9 mini. Do you need configuration files from them, or anything to help add them?

Thanks,

Dave

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by michelem09** [comment]
I'd need the output of the `stats` API call

**Comment by michelem09** [comment]
Please refer to #236

**Comment by FlatEarthDave** [comment]
Is this what you were needing for the output of stats API?

L3++ using blissz firmware:
STATUS=E,When=1539019781,Code=10,Msg=No ,Description=cgminer 4.10.0|root@beaglebone:~#<mailto:4.10.0|root@beaglebone:~#>

Z9 mini:
STATUS=E,When=1539020010,Code=10,Msg=No ,Description=cgminer 4.9.0|root@antMiner:~#

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by michelem09** [comment]
What's the command you used? Can you try with:

`echo -n "summary" | nc ANTIMINER_IP 4028`

**Comment by FlatEarthDave** [comment]
I used echo -n "dev" | nc ANTIMINER_IP 4028

Z9 mini:

Using username "root".

root@192.168.1.12's password:

root@antMiner:~# echo -n "summary" | nc 192.168.1.12 4028

STATUS=S,When=1539026771,Code=11,Msg=Summary,Description=cgminer 4.9.0|SUMMARY,Elapsed=148114,GHS 5s=16.00,GHS av=16.42,Found Blocks=0,Getworks=3392,Accepted=12393,Rejected=134,Hardware Errors=0,Utility=5.02,Discarded=80498,Stale=6,Get Failures=10,Local Work=93918,Remote Failures=4,Network Blocks=1,Total MH=2431689414.0000,Work Utility=81.26,Difficulty Accepted=199517.00000000,Difficulty Rejected=984.00000000,Difficulty Stale=83.00000000,Best Share=0,Device Hardware%=0.0000,Device Rejected%=0.4906,Pool Rejected%=0.4906,Pool Stale%=0.0414,Last getwork=1539026769|root@antMiner:~#
L3++:

login as: root
root@192.168.1.11's password:
root@beaglebone:~# echo -n "summary" | nc 192.168.1.11 4028
STATUS=S,When=1539026926,Code=11,Msg=Summary,Description=cgminer 4.10.0|SUMMARY,Elapsed=148267,GHS 5s=575.247,GHS av=574.08,Found Blocks=28,Getworks=15174,Accepted=6697,Rejected=105,Hardware Errors=1411,Utility=2.71,Discarded=103908,Stale=17,Get Failures=40,Local Work=193034,Remote Failures=2,Network Blocks=10586,Total MH=85117130.0000,Work Utility=529563.92,Difficulty Accepted=1300126975.47027612,Difficulty Rejected=8486509.27696208,Difficulty Stale=0.00000000,Best Share=991459891,Device Hardware%=0.0001,Device Rejected%=0.6485,Pool Rejected%=0.6485,Pool Stale%=0.0000,Last getwork=1539026925|root@beaglebone:~#


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by michelem09** [comment]
Could you kindly run also this command?

`echo -n '{"command":"summary+devs+pools"}' | nc 192.168.1.12 4028`

and

`echo -n '{"command":"summary+devs+pools"}' | nc 192.168.1.11 4028`

**Comment by FlatEarthDave** [comment]
Here’s the Z9 mini, I’ll get you the L3++ a little later. With and without the blissz firmware.


root@antMiner:~# echo -n '{"command":"summary+devs+pools"}' | nc 192.168.1.12 40
28
{"summary":[{"STATUS":[{"STATUS":"S","When":1539087182,"Code":11,"Msg":"Summary","Description":"cgminer 4.9.0"}],"SUMMARY":[{"Elapsed":208526,"GHS 5s":"16.76","GHS av":16.42,"Found Blocks":0,"Getworks":4790,"Accepted":16726,"Rejected":134,"Hardware Errors":0,"Utility":4.81,"Discarded":113412,"Stale":6,"Get Failures":10,"Local Work":132421,"Remote Failures":4,"Network Blocks":1,"Total MH":3424556949.0000,"Work Utility":78.91,"Difficulty Accepted":273178.00000000,"Difficulty Rejected":984.00000000,"Difficulty Stale":83.00000000,"Best Share":0,"Device Hardware%":0.0000,"Device Rejected%":0.3588,"Pool Rejected%":0.3588,"Pool Stale%":0.0303,"Last getwork":1539087181}],"id":1}],"devs":[{"STATUS":[{"STATUS":"E","When":1539087182,"Code":10,"Msg":"No ","Description":"cgminer 4.9.0"}],"id":1}],"pools":[{"STATUS":[{"STATUS":"S","When":1539087182,"Code":7,"Msg":"3 Pool(s)","Description":"cgminer 4.9.0"}],"POOLS":[{"POOL":0,"URL":"stratum+tcp://equihash.mine.zergpool.com:2142","Status":"Alive","Priority":0,"Quota":1,"Long Poll":"N","Getworks":4729,"Accepted":14903,"Rejected":134,"Discarded":112344,"Stale":6,"Get Failures":9,"Remote Failures":4,"User":"3EYGiRngwVKGAWEda6gZhWCYdrZ1w63y8Q","Last Share Time":"0:00:41","Diff":"18","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":252440.00000000,"Difficulty Rejected":984.00000000,"Difficulty Stale":83.00000000,"Last Share Difficulty":18.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"equihash.mine.zergpool.com","Has GBT":false,"Best Share":0,"Pool Rejected%":0.3882,"Pool Stale%":0.0327},{"POOL":1,"URL":"stratum+tcp://us.miningspeed.com:3053","Status":"Alive","Priority":1,"Quota":1,"Long Poll":"N","Getworks":42,"Accepted":1563,"Rejected":0,"Discarded":890,"Stale":0,"Get Failures":1,"Remote Failures":0,"User":"t1ZmuwumqYtPFczUnX7LWVkBuEJGDfhoKjg","Last Share Time":"36:50:40","Diff":"18","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":17618.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":18.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":2,"URL":"stratum+tcp://us-east.zec.slushpool.com:4444","Status":"Alive","Priority":2,"Quota":1,"Long Poll":"N","Getworks":19,"Accepted":260,"Rejected":0,"Discarded":178,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"davidadrake","Last Share Time":"49:53:19","Diff":"16","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":3120.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":16.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000}],root@antMiner:~#

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by michelem09** [comment]
This is very useful! If the above stats are correct I found because Z9 Mini doens't work (it misses a part of stats, the main one)

**Comment by FlatEarthDave** [comment]
L3++ with blissz firmware:


root@beaglebone:~# echo -n '{"command":"summary+devs+pools"}' | nc 192.168.1.11
4028
{"summary":[{"STATUS":[{"STATUS":"S","When":1539134588,"Code":11,"Msg":"Summary","Description":"cgminer 4.10.0"}],"SUMMARY":[{"Elapsed":53,"GHS 5s":"506.95","GHS av":571.07,"Found Blocks":0,"Getworks":17,"Accepted":10,"Rejected":3,"Hardware Errors":1,"Utility":11.24,"Discarded":47,"Stale":0,"Get Failures":0,"Local Work":112,"Remote Failures":0,"Network Blocks":11,"Total MH":30491.0000,"Work Utility":659490.81,"Difficulty Accepted":500000.00000000,"Difficulty Rejected":86863.50000000,"Difficulty Stale":0.00000000,"Best Share":927500,"Device Hardware%":0.0002,"Device Rejected%":14.8013,"Pool Rejected%":14.8013,"Pool Stale%":0.0000,"Last getwork":1539134586}],"id":1}],"devs":[{"STATUS":[{"STATUS":"E","When":1539134588,"Code":10,"Msg":"No ","Description":"cgminer 4.10.0"}],"id":1}],"pools":[{"STATUS":[{"STATUS":"S","When":1539134588,"Code":7,"Msg":"6 Pool(s)","Description":"cgminer 4.10.0"}],"POOLS":[{"POOL":0,"URL":"stratum+tcp://scrypt.mine.zergpool.com:3433","Status":"Alive","Priority":0,"Quota":1,"Long Poll":"N","Getworks":11,"Accepted":10,"Rejected":1,"Discarded":47,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"3EYGiRngwVKGAWEda6gZhWCYdrZ1w63y8Q","Last Share Time":"0:00:01","Diff":"50K","Diff1 Shares":1828,"Proxy Type":"","Proxy":"","Difficulty Accepted":500000.00000000,"Difficulty Rejected":50000.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":50000.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"scrypt.mine.zergpool.com","Has GBT":false,"Best Share":927500,"Pool Rejected%":9.0909,"Pool Stale%":0.0000},{"POOL":1,"URL":"stratum+tcp://node1.guldenpool.nl:27100","Status":"Dead","Priority":1,"Quota":1,"Long Poll":"N","Getworks":0,"Accepted":0,"Rejected":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"GeXtPEwTPDP6KYyUEVKShYUq8fzqUDgBFJ.L3","Last Share Time":"0","Diff":"","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":2,"URL":"stratum+tcp://dgb.brutang.work:5025","Status":"Alive","Priority":2,"Quota":1,"Long Poll":"N","Getworks":3,"Accepted":0,"Rejected":1,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"D6VbE3JZe8WfF7AjLARmXdpkGPZCc3SH3W","Last Share Time":"0","Diff":"32.8K","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":32767.50000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":100.0000,"Pool Stale%":0.0000},{"POOL":3,"URL":"stratum+tcp://us.multipool.us:7777","Status":"Alive","Priority":3,"Quota":1,"Long Poll":"N","Getworks":2,"Accepted":0,"Rejected":1,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"davidadrake.multi","Last Share Time":"0","Diff":"4.1K","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":4096.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":100.0000,"Pool Stale%":0.0000},{"POOL":4,"URL":"stratum+tcp://stratum-ltc.antpool.com:443","Status":"Alive","Priority":4,"Quota":1,"Long Poll":"N","Getworks":1,"Accepted":0,"Rejected":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"davidadrake","Last Share Time":"0","Diff":"","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":5,"URL":"stratum+tcp://hub.miningpoolhub.com:17001","Status":"Alive","Priority":5,"Quota":1,"Long Poll":"N","Getworks":0,"Accepted":0,"Rejected":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"davidadrake.SCRYPT","Last Share Time":"0","Diff":"","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000}],"id":1}],"id":1}root@beaglebone:~#

L3++ stock firmware:

root@antMiner:~# echo -n '{"command":"summary+devs+pools"}' | nc 192.168.1.14 40
28
{"summary":[{"STATUS":[{"STATUS":"S","When":1539135052,"Code":11,"Msg":"Summary","Description":"cgminer 4.9.0"}],"SUMMARY":[{"Elapsed":155,"GHS 5s":"590.85","GHS av":582.71,"Found Blocks":0,"Getworks":9,"Accepted":4,"Rejected":0,"Hardware Errors":9,"Utility":1.55,"Discarded":80,"Stale":0,"Get Failures":0,"Local Work":135,"Remote Failures":0,"Network Blocks":1,"Total MH":90467.0000,"Work Utility":405237.64,"Difficulty Accepted":1048576.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Best Share":6682176,"Device Hardware%":0.0009,"Device Rejected%":0.0000,"Pool Rejected%":0.0000,"Pool Stale%":0.0000,"Last getwork":1539135051}],"id":1}],"devs":[{"STATUS":[{"STATUS":"E","When":1539135052,"Code":10,"Msg":"No ","Description":"cgminer 4.9.0"}],"id":1}],"pools":[{"STATUS":[{"STATUS":"S","When":1539135052,"Code":7,"Msg":"3 Pool(s)","Description":"cgminer 4.9.0"}],"POOLS":[{"POOL":0,"URL":"stratum+tcp://stratum-ltc.antpool.com:8888","Status":"Alive","Priority":0,"Quota":1,"Long Poll":"N","Getworks":5,"Accepted":4,"Rejected":0,"Discarded":80,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"antminer_1","Last Share Time":"0:01:08","Diff":"262K","Diff1 Shares":5420,"Proxy Type":"","Proxy":"","Difficulty Accepted":1048576.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":262144.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"stratum-ltc.antpool.com","Has GBT":false,"Best Share":6682176,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":1,"URL":"stratum+tcp://stratum-ltc.antpool.com:443","Status":"Alive","Priority":1,"Quota":1,"Long Poll":"N","Getworks":2,"Accepted":0,"Rejected":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"antminer_1","Last Share Time":"0","Diff":"","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000},{"POOL":2,"URL":"stratum+tcp://stratum.f2pool.com:8888","Status":"Alive","Priority":2,"Quota":1,"Long Poll":"N","Getworks":2,"Accepted":0,"Rejected":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"ant.123","Last Share Time":"0","Diff":"131K","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000}],"id":1}],"id":1}root@antMiner:~#

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by michelem09** [comment]
Ok thanks! Everything should work now
