### ISSUE TITLE
Support for Antminer Z9-Mini and Z9

### ISSUE THREAD

**Issue by CryptoBlockchainTechnologies** [getminera/minera#236]
Currently trying to get this to work with Z9 mini but do not see Equihash option in Algorythm. Is there support for these?

**Comment by CryptoX** [comment]
Same question here, tried 0.9.0 but look's like no Z9 or Z9-mini support

**Comment by michelem09** [comment]
If someone could send me the output of the stats API call I could add it to Minera.

**Comment by michelem09** [comment]
v0.9.1 should support it

**Comment by grunsel00** [comment]
> If someone could send me the output of the stats API call I could add it to Minera.
> 
> Running this command against an Antminer IP will help me adding them to Minera:
> 
> `echo -n '{"command":"summary+devs+pools"}' | nc ANTIMINER_IP 4028`
> 
> Something like:
> 
> `echo -n '{"command":"summary+devs+pools"}' | nc 192.168.0.10 4028`

This is my outcome: from Antminer S15
echo -n '{"command":"summary+devs+pools"}' | nc 192.168.99.90 4028                                                                                                              
{"summary":[{"STATUS":[{"STATUS":"S","When":1568884576,"Code":11,"Msg":"Summary","Description":"cgminer 4.9.0"}],"SUMMARY":[{"Elapsed":1301337,"GHS 5s":"28982.24","GHS av":28388.72,"Found Blocks
":0,"Getworks":21422,"Accepted":76504,"Rejected":73,"Hardware Errors":46119,"Utility":3.53,"Discarded":673192,"Stale":56,"Get Failures":68,"Local Work":135118246,"Remote Failures":5,"Network Blo
cks":2407,"Total MH":36935045519229.0000,"Work Utility":396314.08,"Difficulty Accepted":8587313152.00000000,"Difficulty Rejected":8323072.00000000,"Difficulty Stale":0.00000000,"Best Share":8118
956762,"Device Hardware%":0.0005,"Device Rejected%":0.0968,"Pool Rejected%":0.0968,"Pool Stale%":0.0000,"Last getwork":1568884575}],"id":1}],"devs":[{"STATUS":[{"STATUS":"S","When":1568884576,"C
ode":9,"Msg":"1 ASC(s)","Description":"cgminer 4.9.0"}],"DEVS":[{"ASC":0,"Name":"BTM_SOC","ID":0,"Enabled":"Y","Status":"Alive","Temperature":0.00,"MHS av":28382383.29,"MHS 5s":28977484.40,"Acce
pted":76504,"Rejected":73,"Hardware Errors":46119,"Utility":3.53,"Last Share Pool":0,"Last Share Time":1568884559,"Total MH":36935045519229.0000,"Diff1 Work":0,"Difficulty Accepted":8587313152.0
0000000,"Difficulty Rejected":8323072.00000000,"Last Share Difficulty":65536.00000000,"Last Valid Work":1568884559,"Device Hardware%":100.0000,"Device Rejected%":0.0000,"Device Elapsed":1301337}
],"id":1}],"pools":[{"STATUS":[{"STATUS":"S","When":1568884576,"Code":7,"Msg":"3 Pool(s)","Description":"cgminer 4.9.0"}],"POOLS":[{"POOL":0,"URL":"stratum+tcp://eu.ss.btc.com:1800","Status":"Al
ive","Priority":0,"Quota":1,"Long Poll":"N","Getworks":21398,"Accepted":76472,"Rejected":73,"Discarded":673057,"Stale":34,"Get Failures":66,"Remote Failures":5,"User":"***********","Last Shar
e Time":"0:00:17","Diff":"65.5K","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":8585216000.00000000,"Difficulty Rejected":8323072.00000000,"Difficulty Stale":0.00000000,"Last 
Share Difficulty":65536.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"eu.ss.btc.com","Has GBT":false,"Best Share":8118956762,"Pool Rejected%":0.0969,"Pool Stale%":0.0000},{"PO
OL":1,"URL":"stratum+tcp://eu.ss.btc.com:443","Status":"Alive","Priority":1,"Quota":1,"Long Poll":"N","Getworks":13,"Accepted":1,"Rejected":0,"Discarded":1,"Stale":8,"Get Failures":2,"Remote Fai
lures":0,"User":"************","Last Share Time":"361:28:47","Diff":"65.5K","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":65536.00000000,"Difficulty Rejected":0.00000000,"D
ifficulty Stale":0.00000000,"Last Share Difficulty":65536.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":2636571,"Pool Rejected%":0.0000,"Pool S
tale%":0.0000},{"POOL":2,"URL":"stratum+tcp://eu.ss.btc.com:25","Status":"Alive","Priority":2,"Quota":1,"Long Poll":"N","Getworks":11,"Accepted":31,"Rejected":0,"Discarded":134,"Stale":14,"Get F
ailures":0,"Remote Failures":0,"User":"**********","Last Share Time":"3:19:30","Diff":"65.5K","Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":2031616.00000000,"Difficulty R
ejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":65536.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":29265343,"Pool Re
jected%":0.0000,"Pool Stale%":0.0000}],"id":1}],"id":1}minera@minera:~ $

**Comment by lurchinms** [comment]
BitMain S3
`{"summary":[{"STATUS":[{"STATUS":"S","When":1575944080,"Code":11,"Msg":"Summary","Description":"cgminer 4.9.2"}],"SUMMARY":[{"Elapsed":18955,"MHS av":381450.21,"MHS 5s":181714.21,"MHS 1m":400660.56,"MHS 5m":392907.09,"MHS 15m":402917.81,"Found Blocks":0,"Getworks":761,"Accepted":187,"Rejected":0,"Hardware Errors":86,"Utility":0.59,"Discarded":1885793,"Stale":0,"Get Failures":1,"Local Work":3785350,"Remote Failures":0,"Network Blocks":25,"Total MH":7230388446.0000,"Work Utility":5328.80,"Difficulty Accepted":1531904.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Best Share":2656081,"Device Hardware%":0.0051,"Device Rejected%":0.0000,"Pool Rejected%":0.0000,"Pool Stale%":0.0000,"Last getwork":1575944080}],"id":1}],"devs":[{"STATUS":[{"STATUS":"S","When":1575944080,"Code":9,"Msg":"1 ASC(s)","Description":"cgminer 4.9.2"}],"DEVS":[{"ASC":0,"Name":"AS3","ID":0,"Enabled":"Y","Status":"Alive","Temperature":40.00,"MHS av":381450.21,"MHS 5s":181714.21,"MHS 1m":400660.56,"MHS 5m":392907.09,"MHS 15m":402917.81,"Accepted":187,"Rejected":0,"Hardware Errors":86,"Utility":0.59,"Last Share Pool":0,"Last Share Time":1575944057,"Total MH":7230388446.0000,"Diff1 Work":1683456,"Difficulty Accepted":1531904.00000000,"Difficulty Rejected":0.00000000,"Last Share Difficulty":8192.00000000,"No Device":false,"Last Valid Work":1575944058,"Device Hardware%":0.0051,"Device Rejected%":0.0000,"Device Elapsed":18955}],"id":1}],"pools":[{"STATUS":[{"STATUS":"S","When":1575944080,"Code":7,"Msg":"2 Pool(s)","Description":"cgminer 4.9.2"}],"POOLS":[{"POOL":0,"URL":"stratum+tcp://btc.ss.poolin.com:443","Status":"Alive","Priority":0,"Quota":1,"Long Poll":"N","Getworks":758,"Accepted":187,"Rejected":0,"Works":1899505,"Discarded":1885793,"Stale":0,"Get Failures":1,"Remote Failures":0,"User":"kriptoking.001","Last Share Time":1575944057,"Diff1 Shares":1683456,"Proxy Type":"","Proxy":"","Difficulty Accepted":1531904.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":8192.00000000,"Has Stratum":true,"Stratum Active":true,"Stratum URL":"btc.ss.poolin.com","Has GBT":false,"Best Share":2656081,"Pool Rejected%":0.0000,"Pool Stale%":0.0000,"Bad Work":0},{"POOL":1,"URL":"stratum+tcp://btc.ss.poolin.com:1883","Status":"Alive","Priority":1,"Quota":1,"Long Poll":"N","Getworks":3,"Accepted":0,"Rejected":0,"Works":0,"Discarded":0,"Stale":0,"Get Failures":0,"Remote Failures":0,"User":"kriptoking.001","Last Share Time":0,"Diff1 Shares":0,"Proxy Type":"","Proxy":"","Difficulty Accepted":0.00000000,"Difficulty Rejected":0.00000000,"Difficulty Stale":0.00000000,"Last Share Difficulty":0.00000000,"Has Stratum":true,"Stratum Active":false,"Stratum URL":"","Has GBT":false,"Best Share":0,"Pool Rejected%":0.0000,"Pool Stale%":0.0000,"Bad Work":0}],"id":1}],"id":1}`
