### ISSUE TITLE
G A R B A G E - S C R I P T - Install Coinhive trojan/Virus and tells you to unblock it.

### ISSUE THREAD

**Issue by Illustratum** [getminera/minera#237]
**Describe the bug**

Minera is the bug.

FIX: Remove the whole shit (Format the SD card, burn it also)

**To Reproduce**

Install over and over and over until you understand it's pretty shit.

**Expected behavior**

Expected nothing from greedy kids throwing coinhive virus/trojan around.

**Screenshots**

Phone crashes when tainted pixels from robber baron softwares are released like this.

**Desktop (please complete the following information):**

 - OS: All
 - Browser All
 - Version Latest Crap

**Smartphone (please complete the following information):**

 - Device: All
 - OS: All
 - Browser All
 - Version Latest

**Additional context**

God you have lost so many Users/customers with this Coinhive ball sucking.

I still hear those sucking sounds.

Cringe.

**Comment by michelem09** [comment]
You can simply disable it but yes I'll remove it



Il giorno lun 3 dic 2018 alle 06:59 Illustratum <notifications@github.com>
ha scritto:
