### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by debpedrano** [getminera/minera#238]
Greetings!

I am an aspiring graphics designer and I have some designs for your project, I can show you the design if you wanted to do so.

**Comment by michelem09** [comment]
Sure! Please let me see. Thanks

**Comment by debpedrano** [comment]
@michelem09  , what font does the word MINERA is using?

**Comment by michelem09** [comment]
It's this one: "Kaushan Script" https://fonts.google.com/specimen/Kaushan+Script

**Comment by debpedrano** [comment]
@michelem09  how about this one?

![image](https://user-images.githubusercontent.com/40510200/50508933-de3b4100-0abe-11e9-9c0f-199e68860495.png)

**Comment by michelem09** [comment]
Pretty cool, I'd like to see also the Minera text with it and may be something related to a M in the logo. Is it possible?

**Comment by debpedrano** [comment]
Ill make some changes @michelem09

**Comment by debpedrano** [comment]
I made it simpler, the letter M signifies the project.  @michelem09 

First Design :

![image](https://user-images.githubusercontent.com/40510200/50516316-16ee1100-0ae5-11e9-84e1-20812a906b97.png)

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/50517314-dabdaf00-0aea-11e9-82c7-beba7c4b715b.png)

**Comment by michelem09** [comment]
Thanks @debpedrano I like the circled one

**Comment by debpedrano** [comment]
![image](https://user-images.githubusercontent.com/40510200/50538315-a01a4c00-0ba8-11e9-9ba9-bd13f1f72ffd.png)

**Comment by debpedrano** [comment]
@michelem09 just tell where it is so that I can make a PR :) take your time..

**Comment by debpedrano** [comment]
@michelem09 take your time in choosing :) Ill make a PR after you've picked your choice.

**Comment by debpedrano** [comment]
@michelem09  any update?

**Comment by michelem09** [comment]
I think I'll go with this version https://user-images.githubusercontent.com/40510200/50538315-a01a4c00-0ba8-11e9-9ba9-bd13f1f72ffd.png

**Comment by michelem09** [comment]
Please do the `logo` dir inside `assets/img/` if you can.

**Comment by debpedrano** [comment]
@michelem09  since i already submitted the design, i have this on my mind a new one. maybe you can use this in the near future or as a back-up logo, just reply. ill be gladly to show you the design.

**Comment by michelem09** [comment]
Sure @debpedrano let me see, thanks
