### ISSUE TITLE
Minera G-blade

### ISSUE THREAD

**Issue by cdavid53** [getminera/minera#242]
Hello

sorry in advance for my english i am french and i use a translator.
My problem is that I can not get past Dev HR in green and have tried a lot of different setup, I have two gridseed g-blade plugged in a raspberry. if someone has an idea I'm interested because after two days I'm running out of ideas

thank you in advance

**Comment by michelem09** [comment]
1) try your options directly from the command line of your Minera Raspberry if you can
2) Better if you ask to miner author (I don't know what miner software you are using without any info)

**Comment by cdavid53** [comment]
I try all the software included in Minera

**Comment by cdavid53** [comment]
basically i'm using cpuminer, bfgminer or cminminer included in minera but gridseed g-blade does not work properly the Dev HR stays in gray
