### ISSUE TITLE
url not found

### ISSUE THREAD

**Issue by iainanderson924** [getminera/minera#245]
i have installed minera successfully and checked its there in my rpi 4.
when i type the url 192.168.1.9/minera 
i get url not found
i have searched repeatedly for this problem which appears to be fairly common and nowhere has anyone actually solved the problem

when i enter 192.168.1.9 without the /minera i get the standard apachi web page so i know the problem lies with minera which is index.html in the www directory

checking the minera directory there are no html pages listed

**Comment by michelem09** [comment]
Minera requires PHP and default installation relays on Lighttp web server not Apache. You need to configure your Apache to use it.
Try to use the Minera img instead installing it manually.
