### ISSUE TITLE
install_minera_ubuntu.sh fails to install many dependencies

### ISSUE THREAD

**Issue by danb35** [getminera/minera#246]
**Describe the bug**
The `install_minera_ubuntu.sh` script doesn't install dependencies to build the miners.  As a result, none of the miners are built, and Minera doesn't run.

**To Reproduce**

* Install Ubuntu Server 18.04 into a test VM, enabling only "OpenSSH server" from the menu
* Update to latest packages (`apt update && apt upgrade`)
* curl -o- https://raw.githubusercontent.com/getminera/minera/master/install_minera_ubuntu.sh | sudo bash
* See end of output:
```
Building miners, this will take loooooooot of time in a low resource system, I strongly suggest you to take a beer (better two) and relax a while. Your Minera will be ready after this.
-----

cpuminer
Cloning repo https://github.com/siklon/cpuminer-gc3355 into /var/www/minera/minera-bin/src/cpuminer-gc3355
Cloning into '/var/www/minera/minera-bin/src/cpuminer-gc3355'...
remote: Enumerating objects: 862, done.
remote: Total 862 (delta 0), reused 0 (delta 0), pack-reused 862
Receiving objects: 100% (862/862), 4.71 MiB | 3.69 MiB/s, done.
Resolving deltas: 100% (359/359), done.
./autogen.sh: 8: ./autogen.sh: aclocal: not found
DONE! Minera is ready!

Open the URL: http://192.168.1.196/minera/
```

**Expected behavior**
I'd be able to browse to the URL noted and see the Minera page.

**Actual behavior**
Connection refused at that URL.  Noting the compile error, I tried to track down the missing dependencies.  Thus far, I've installed `autotools-dev`, `automake`, `build-essential`, `libcurl4-openssl-dev`, and `libudev-dev`.  It gets farther each attempt, but now it's stopping at:
```
Running autoreconf -if...
configure.ac:35: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
configure.ac:29: warning: AM_PATH_LIBGCRYPT missing; CLI tool will not be available
configure.ac:29: warning: AM_PATH_LIBGCRYPT missing; CLI tool will not be available
configure.ac:29: warning: AM_PATH_LIBGCRYPT missing; CLI tool will not be available
configure.ac:29: warning: AM_PATH_LIBGCRYPT missing; CLI tool will not be available
configure.ac:17: installing './ar-lib'
configure.ac:16: installing './compile'
configure.ac:13: installing './install-sh'
configure.ac:13: installing './missing'
Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:6:   its definition is in aclocal's search path.
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
```

At a minimum, document the dependencies of the install script.  Better yet, install them all in the script--it won't hurt anything to do `apt install foo` if `foo` is already installed

**Comment by michelem09** [comment]
Minera is not compatible with Ubuntu 18.04, just use 16.04

**Comment by minermartelli** [comment]
read my post...probably help you..  :-)
