### ISSUE TITLE
Complete script for install minera on ubuntu 16

### ISSUE THREAD

**Issue by minermartelli** [getminera/minera#248]
hi!
After many and many tentative to install minera...i write a a simple script for automate all, i hope is usefull..

sorry for sleep command is only used for see how macro working, it's possible to remove.
i test it on 3 installation without any problem, used ubuntu 16/lubuntu 16 and xubuntu all on 32 bit, it' install all it' necessary to work and compile miner.
for launch it,is necessary to start it in a terminal with root privilege.

if you have any question i'm here.

Moreno
++++++++++++++++++++++++++++++++++++++++++++++++++++++

#/bin/sh

apt-get -y update
sleep 2
apt-get -y upgrade
sleep 2
apt-get install -y openssh-server
sleep 2
apt-get install -y git
sleep 2
apt-get install -y libssl-dev
sleep 2
apt-get install -y libcurl4-openssl-dev
sleep 2
apt-get install -y automake
sleep 2
apt-get install -y g++ 5.4
sleep 2
apt-get install -y build-essential
sleep 2
apt-get install -y autoconf
sleep 2
apt-get install -y libtool
sleep 2
apt-get install -y libjansson-dev
sleep 2
apt-get install -y libcurl4-gnutls-dev
sleep 2
apt-get install -y libncurses5-dev
sleep 2
apt-get install -y libudev-dev
sleep 2
apt-get install -y libusb-1.0-0-dev
sleep 2
apt-get install -y uthash-dev
sleep 2
apt-get install -y libgcrypt20-dev
sleep 2
apt-get install -y autoconf
sleep 2
apt-get install -y automake
sleep 2
apt-get install -y pkg-config
sleep 2
apt-get install -y libncursesw5-dev
sleep 2
apt-get install -y libevent-dev
sleep 2
apt-get install -y libmicrohttpd-dev
sleep 2
apt-get install -y libhidapi-dev
sleep 2
apt-get install -y libevent-dev
sleep 2
apt-get install -y libi2c-dev
sleep 2
apt-get install -y yasm
sleep 2
apt-get install -y libevent-dev
sleep 2
apt-get install -y software-properties-common
sleep 2
add-apt-repository -y ppa:bitcoin/bitcoin
sleep 2
apt -y update
sleep 2
apt -y upgrade
sleep 2
apt -y autoremove
sleep 2

#installazione apache2

apt-get install -y apache2 
sleep 2
systemctl start apache2.service

#installazione PHP su apache2
sleep 2
apt-get install -y php 
sleep 2
apt-get install -y php-{bcmath,bz2,intl,gd,mbstring,mcrypt,mysql,zip} && apt-get install libapache2-mod-php  -y
sleep 2
#attivazione apache al boot

systemctl enable apache2.service
sleep 2
systemctl enable mysql.service
sleep 2
#restart apache
sleep 2
systemctl restart apache2.service
sleep 2
#installazione minera

apt-get install -y redis-server git screen php7.0-cli php7.0-curl
sleep 2
cd /var/www
sleep 2
git clone https://github.com/getminera/minera
sleep 2
cd minera
sleep 2
./install_minera.sh

#fine
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by mediageni** [comment]
Can I use this on my Raspberry Pi 4?

**Comment by minermartelli** [comment]
I use it only on pc,for raspberry is mandatory use  the raspberry version of ubuntu14.
I think is only wasted time today...
There is no new versione the project is abandoned on the web site.

Scarica Outlook per Android<https://aka.ms/AAb9ysg>

________________________________
